# How should the data be stored from this plugin?
# json - Store locally with the help of json on your server (DEFAULT)
data: json

# How should the plugin display all team features to the player
# chat - Send all information with the help of chat messages (DEFAULT)
# gui - Display information with the help of GUI's
team: chat

lang:
  prefix: "§8§l| §b§lTEAMS §8§l|§r "

  cmd-unknown-sub-command: '&7The command &c/{FULL_COMMAND} &7does not exist.'
  cmd-invalid-argument: '&7Invalid argument, please try another one.'
  cmd-not-enough-args: '&7The command has too few arguments.'
  cmd-too-many-args: '&7The command has too many arguments.'